# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: golangci-lint
        name: golangci-lint
        description: Fast linters runner for Go.
        entry: cd src/bkauth && golangci-lint run --fix
        files: src/bkauth/
        types: [go]
        language: golang
        pass_filenames: false
      - id: golang-unittest
        name: golang-unittest
        description: Golang unittest.
        entry:  cd src/bkauth && make test
        files: src/bkauth/
        types: [go]
        language: golang
        pass_filenames: false
